<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup> 
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <ProjectReference Include="..\..\..\OxyPlot.Avalonia\OxyPlot.Avalonia.csproj" />
    <PackageReference Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageReference Include="Avalonia.Themes.Simple" Version="$(AvaloniaVersion)" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.0" />
  </ItemGroup>
</Project>